server:
  port: 8999
  
  

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://192.168.2.79:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service  
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**